## Repetitions Quiz

In [ ]:
y  = [(1,2),(3,4),(5,6)]

ls = [x**2 for z in y for x in z]
print(ls)

[1, 4, 9, 16, 25, 36]

In [ ]:
name = 'NAME NAME'
x = name.split()
print( x, type(x))

['NAME', 'NAME'] <class 'list'>

In [10]:
print(name.strip())

NAME NAME

**Frage:** wie bekomme ich elegant den whitespace weg?

In [11]:
print(name.replace(' ',''))

NAMENAME

In [18]:
import pandas as pd

# 1. Die CSV-Datei einlesen
df = pd.read_csv('produkte.csv')

# 2. Die ersten Zeilen der Daten anzeigen
print("--- Die ersten 5 Zeilen der Daten ---")
df.head()

--- Die ersten 5 Zeilen der Daten ---

    Produkt  Preis  Bestand      Kategorie
0     Apfel    0.5      100           Obst
1    Orange    0.3      150           Obst
2   Kirsche    2.5       50           Obst
3    Dattel    1.2       20  Trockenfrucht
4  Erdbeere    3.0       80           Obst

In [21]:
# Was macht diese Zeile?? (1)
df['XXX'] = df['Preis'] * df['Bestand']

# Welche Werte haben value1/2?
value1 = df[df['Preis'] > 1.0]


value2 = df['Produkt'][3]

In [24]:
print('wir haben in XX den totalen warenWert im lager des jewiligen produktes berechnet')
df.head()

wir haben in XX den totalen warenWert im lager des jewiligen produktes berechnet

    Produkt  Preis  Bestand      Kategorie    XXX
0     Apfel    0.5      100           Obst   50.0
1    Orange    0.3      150           Obst   45.0
2   Kirsche    2.5       50           Obst  125.0
3    Dattel    1.2       20  Trockenfrucht   24.0
4  Erdbeere    3.0       80           Obst  240.0

In [27]:
print('value2:',value2)
print('Value1: nach preis über 1CHF gefiltert')
value1.head()

value2: Dattel
Value1: nach preis über 1CHF gefiltert

    Produkt  Preis  Bestand      Kategorie    XXX
2   Kirsche    2.5       50           Obst  125.0
3    Dattel    1.2       20  Trockenfrucht   24.0
4  Erdbeere    3.0       80           Obst  240.0

## Rekurisons Refresher

**iterative** Lösung Fakultät

In [ ]:
def it_factulty(n):
    factorial=1
    for i in range(1,n+1): #+1 wegen exklusiven ende
        factorial*=i
    return factorial
it_factulty(4)

24

In [5]:
funktionen_im_stack = 0

def factorial(n):
    global funktionen_im_stack #nur fürs tracking, müsst nicht teil des kurses.
    funktionen_im_stack+=1
    print(f'es sind jetzt {funktionen_im_stack} calls offen')
    # 1. DER BASISFALL (Base Case)
    if n <= 1: #bekanntes erignis
        print(f"Basisfall erreicht: fakultät({n}) gibt 1 zurück.")
        return 1
    
    # 2. DER REKURSIONSSCHRITT (Recursive Step)
    else:
        print(f"Berechne: {n} * fakultaet({n-1})")
        ergebnis = n * factorial(n - 1)

        # Wenn der Basisfall erreicht wurde, "rollt" sich der Stapel von unten nach oben auf.
        funktionen_im_stack-=1
        print(f"Rückkehr aus dem Aufruf: fakultaet({n}) ist {ergebnis}", f'   berechnung erfolgte durch {n}*factorial({n-1})')
        print('es sind noch',funktionen_im_stack,'calls offen')
        return ergebnis

# Beispielaufruf
zahl = 3
print(f"Endergebnis von {zahl}! ist: {factorial(zahl)}")

es sind jetzt 1 calls offen
Berechne: 3 * fakultaet(2)
es sind jetzt 2 calls offen
Berechne: 2 * fakultaet(1)
es sind jetzt 3 calls offen
Basisfall erreicht: fakultät(1) gibt 1 zurück.
Rückkehr aus dem Aufruf: fakultaet(2) ist 2    berechnung erfolgte durch 2*factorial(1)
es sind noch 2 calls offen
Rückkehr aus dem Aufruf: fakultaet(3) ist 6    berechnung erfolgte durch 3*factorial(2)
es sind noch 1 calls offen
Endergebnis von 3! ist: 6

## Dynamic Programming

In [ ]:
def fibonacci_iterative_table(n):
    if n <= 1:
        return n
    
    # Initialisierung der Tabelle (DP-Speicher)
    # Wir erstellen eine Liste der Länge n + 1
    dp = [0] * (n + 1)
    dp[1] = 1
    
    # Schrittweiser Aufbau der Lösung (Bottom-Up)
    for i in range(2, n + 1):
        dp[i] = dp[i-1] + dp[i-2]
        
    return dp[n]

wir brauchen aber eigentlich nur die letzten zwei Werte, (optimeirte Version)

In [ ]:
def fibonacci_optimized(n):
    if n <= 1:
        return n
    
    # Wir speichern nur die letzten zwei Werte statt einer ganzen Liste
    prev2 = 0  # fib(i-2)
    prev1 = 1  # fib(i-1)
    
    for _ in range(2, n + 1):
        current = prev1 + prev2
        # Werte für den nächsten Durchlauf verschieben
        prev2 = prev1
        prev1 = current
        
    return prev1